const students = [
  { roll_no: 23201, name: 'Vaibhav Sharma', hostel_name: 'Bhutagni' },
  { roll_no: 23202, name: 'Utkarsh Verma', hostel_name: 'Chitaghni' },
  { roll_no: 23203, name: 'Tushar Barnwal', hostel_name: 'Jathragni' },
  { roll_no: 23204, name: 'Anaya Verma', hostel_name: 'Bhutagni' },
  { roll_no: 23205, name: 'Kabir Singh', hostel_name: 'Chitaghni' },
  { roll_no: 23206, name: 'Riya Malhotra', hostel_name: 'Jathragni' },
  { roll_no: 23207, name: 'Aryan Joshi', hostel_name: 'Bhutagni' },
  { roll_no: 23208, name: 'Mira Kapoor', hostel_name: 'Chitaghni' },
  { roll_no: 23209, name: 'Dev Patel', hostel_name: 'Jathragni' },
  { roll_no: 23210, name: 'Sanya Roy', hostel_name: 'Bhutagni' },
  { roll_no: 23112, name: 'Arpit Kumar', hostel_name: 'Bhutagni' },
  { roll_no: 23211, name: 'Aarav Mehta', hostel_name: 'Chitaghni' },
  { roll_no: 23212, name: 'Ishaan Sharma', hostel_name: 'Jathragni' },
  { roll_no: 23213, name: 'Neha Gupta', hostel_name: 'Bhutagni' },
  { roll_no: 23214, name: 'Samar Saxena', hostel_name: 'Chitaghni' },
  { roll_no: 23215, name: 'Tushar barnwal', hostel_name: 'Jathragni' },
  { roll_no: 23216, name: 'Rajesh Yadav', hostel_name: 'Bhutagni' },
  { roll_no: 23217, name: 'Priya Sen', hostel_name: 'Chitaghni' },
  { roll_no: 23218, name: 'Rohan Das', hostel_name: 'Jathragni' },
  { roll_no: 23219, name: 'Nidhi Khatri', hostel_name: 'Bhutagni' },
  { roll_no: 23220, name: 'Kunal Bhardwaj', hostel_name: 'Chitaghni' },
  { roll_no: 23221, name: 'Aditi Rao', hostel_name: 'Jathragni' },
  { roll_no: 23222, name: 'Harsh Vardhan', hostel_name: 'Bhutagni' },
  { roll_no: 23223, name: 'Sneha Mishra', hostel_name: 'Chitaghni' },
  { roll_no: 23224, name: 'Rahul Taneja', hostel_name: 'Jathragni' },
  { roll_no: 23225, name: 'Anushka Jain', hostel_name: 'Bhutagni' },
  { roll_no: 23226, name: 'Yuvraj Malhotra', hostel_name: 'Chitaghni' },
  { roll_no: 23227, name: 'Esha Kaur', hostel_name: 'Jathragni' },
  { roll_no: 23228, name: 'Gautam Tripathi', hostel_name: 'Bhutagni' },
  { roll_no: 23229, name: 'Pooja Chauhan', hostel_name: 'Chitaghni' },
  { roll_no: 23230, name: 'Rishi Khanna', hostel_name: 'Jathragni' },
  { roll_no: 23231, name: 'Ayesha Sheikh', hostel_name: 'Bhutagni' },
  { roll_no: 23232, name: 'Mohit Bansal', hostel_name: 'Chitaghni' },
  { roll_no: 23233, name: 'Sakshi Nair', hostel_name: 'Jathragni' },
  { roll_no: 23234, name: 'Karan Gill', hostel_name: 'Bhutagni' },
  { roll_no: 23235, name: 'Lavanya Arora', hostel_name: 'Chitaghni' },
  { roll_no: 23236, name: 'Manoj Thakur', hostel_name: 'Jathragni' },
  { roll_no: 23237, name: 'Parth Oberoi', hostel_name: 'Bhutagni' },
  { roll_no: 23238, name: 'Divya Rathi', hostel_name: 'Chitaghni' },
  { roll_no: 23239, name: 'Siddharth Grover', hostel_name: 'Jathragni' },
  { roll_no: 23240, name: 'Simran Bhatia', hostel_name: 'Bhutagni' },
  { roll_no: 23241, name: 'Varun Kapoor', hostel_name: 'Chitaghni' },
  { roll_no: 23242, name: 'Meenal Sethi', hostel_name: 'Jathragni' },
  { roll_no: 23243, name: 'Jatin Chopra', hostel_name: 'Bhutagni' },
  { roll_no: 23244, name: 'Alok Choudhary', hostel_name: 'Chitaghni' },
  { roll_no: 23245, name: 'Tanya Mehta', hostel_name: 'Jathragni' },
  { roll_no: 23246, name: 'Arjun Sharma', hostel_name: 'Bhutagni' },
  { roll_no: 23247, name: 'Preeti Sinha', hostel_name: 'Chitaghni' },
  { roll_no: 23248, name: 'Sauraj kumar srivastava', hostel_name: 'Bhutagni' },
  { roll_no: 23249, name: 'Rachit Dixit', hostel_name: 'Bhutagni' },
  { roll_no: 23250, name: 'Swati Pandey', hostel_name: 'Chitaghni' },
  { roll_no: 23251, name: 'Tanmay Rana', hostel_name: 'Jathragni' },
  { roll_no: 23252, name: 'Ishita Malik', hostel_name: 'Bhutagni' },
  { roll_no: 23253, name: 'Aniket Joshi', hostel_name: 'Chitaghni' },
  { roll_no: 23254, name: 'Sonali Chatterjee', hostel_name: 'Jathragni' },
  { roll_no: 23255, name: 'Neeraj Soni', hostel_name: 'Bhutagni' },
  { roll_no: 23256, name: 'Bhavya Sharma', hostel_name: 'Chitaghni' },
  { roll_no: 23257, name: 'Utkarsh Rajput', hostel_name: 'Bhutagni' },
  { roll_no: 23258, name: 'Vaibhav sharma', hostel_name: 'Bhutagni' },
  { roll_no: 23259, name: 'Vikas Agrawal', hostel_name: 'Chitaghni' },
  { roll_no: 23260, name: 'Reema Dutta', hostel_name: 'Jathragni' },
  { roll_no: 23261, name: 'Chetan Rawat', hostel_name: 'Bhutagni' },
  { roll_no: 23262, name: 'Ritu Bansal', hostel_name: 'Chitaghni' },
];



const entries= [
  // {destination: "jj mode", student: '679d538b606fcf0a51164d33'},
  // {destination: "jj mode", student: '679b60ada7e81147039fa75e'},
];

module.exports = {data: students, data2: entries};
